# deployment and service in 1 file because they belong together
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels:
    app: mongo
spec:   # Deploment specific config
  replicas: 3
  selector:
    matchLabels:
      app: mongo
  template:   # main part: blueprint/config of the pod
  # has its own "metadata" and "spec"
    metadata:
      labels:
        app: mongo
    spec:
      containers: # mostly one main app per pod
      - name: mongodb
        image: mongo:4.4
        ports:
        - containerPort: 27017
