# deployment and service in 1 file because they belong together
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels:
    app: mongo
spec:   # Deploment specific config
  replicas: 1   # how many Pods want to create using this blueprint
  selector:
    matchLabels:
      app: mongo
  template:   # main part: blueprint/config of the pod
  # has its own "metadata" and "spec"
    metadata:
      labels:
        app: mongo
    spec:
      containers: # mostly one main app per pod
      - name: mongodb
        image: mongo:4.4
        ports:
        - containerPort: 27017
---   # have multiple YAML configurations within 1 file
# Service
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:   # Select Pods to forward the request => connect service to pods
    app: mongo
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 27017
