apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:   # value has to be encoding first
# encoding with terminal: echo -n mongouser | base64
  mongo-user: bW9uZ291c2Vy
  mongo-password:
