# deployment and service in 1 file because they belong together
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:   # Deploment specific config
  replicas: 1   # how many Pods want to create using this blueprint
  selector:
    matchLabels:
      app: webapp
  template:   # main part: blueprint/config of the pod
  # has its own "metadata" and "spec"
    metadata:
      labels:
        app: webapp
    spec:
      containers: # mostly one main app per pod
      - name: webapp
        image: nanajanashia/k8s-demo-app:v1.0
        ports:
        - containerPort: 3000
        env:
        - name: USER_NAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-user
        - name: USER_PWD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-password
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: mongo-url


---   # have multiple YAML configurations within 1 file
# Service
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  selector:   # Select Pods to forward the request => connect service to pods
    app: webapp
  ports:
    - protocol: TCP
      port: 3000   # common standard to use same as target port
      targetPort: 3000   # containerPort of Deployment
